test_that("policy pathway export writes reproducible analytical artifacts", {
  optimization <- optimize_policy(policy_spec_fixture(), policy_evaluator_fixture)
  pathway <- policy_pathway_fixture()
  evidence <- data.frame(time = c(2027, 2030), emissions = c(92, 72), jobs = c(50, 44))
  evaluation <- evaluate_policy_pathway(pathway, evidence)
  options <- data.frame(option = c("efficiency", "renewables"), cost = c(20, 45), effect = c(10, 25), abatement = c(10, 20))
  analysis <- policy_pathway_analysis(optimization, pathway, evaluation, cost_effectiveness = cost_effectiveness_analysis(options), marginal_abatement = marginal_abatement_curve(options))
  dir <- tempfile("policy-export-"); dir.create(dir)
  paths <- export_policy_pathway_analysis(analysis, dir = dir, prefix = "policy", zip_bundle = FALSE)
  expect_true(file.exists(paths$analysis)); expect_true(file.exists(paths$candidates)); expect_true(file.exists(paths$pareto)); expect_true(file.exists(paths$manifest))
  manifest <- jsonlite::fromJSON(paths$manifest)
  expect_identical(manifest$package$version, "1.3.0")
  expect_true(manifest$boundary$recommendation_not_authorization)
  expect_true(manifest$file_count >= 8L)
})
