test_that("connected platform indexes projects, evidence, decisions, and lineage", {
  platform <- connected_sustainability_platform("platform-1", "Platform One", "institution-1", "Institution One")
  project <- project_fixture()
  platform <- platform_add_project(platform, project)
  evidence <- platform_evidence_record("evidence-1", "Baseline evidence", "dataset", list(dataset_id = "baseline"), quality_status = "verified")
  platform <- platform_register_records(platform, "evidence", list(`evidence-1` = evidence))
  decision <- platform_decision_record("decision-1", "Policy decision", c("baseline", "policy"), evidence_ids = "evidence-1")
  platform <- platform_add_decision(platform, decision)
  expect_s3_class(platform, "catalyst_connected_platform")
  expect_true("project.transition-evidence" %in% names(platform$nodes))
  expect_true("decision.decision-1" %in% names(platform$nodes))
  lineage <- platform_lineage(platform, "decision.decision-1", "upstream")
  expect_true("registry.evidence.evidence.evidence-1" %in% lineage$node_ids)
  expect_true(connected_platform_summary(platform)$human_review_required)
})

test_that("connected platform JSON and publication bundles preserve contracts", {
  platform <- connected_sustainability_platform("platform-json", "JSON Platform", "institution-1", "Institution One")
  platform <- platform_add_project(platform, project_fixture())
  path <- tempfile(fileext = ".json")
  original_fingerprint <- connected_platform_fingerprint(platform)
  connected_platform_to_json(platform, path)
  serialized <- jsonlite::read_json(path, simplifyVector = FALSE)
  expect_identical(serialized$metadata$serialized_platform_fingerprint, original_fingerprint)
  expect_false(any(grepl("^\\.restored_connected_platform_", names(serialized))))
  restored <- connected_platform_from_json(path)
  expect_s3_class(restored, "catalyst_connected_platform")
  expect_identical(restored$id, platform$id)
  expect_identical(connected_platform_fingerprint(restored), original_fingerprint)
  changed <- platform_add_node(restored, platform_node("external-source-1", "external_source", "External source"))
  expect_false(identical(connected_platform_fingerprint(changed), original_fingerprint))
  out <- tempfile("connected-export-")
  paths <- export_connected_platform(platform, out, zip_bundle = FALSE)
  expect_true(all(file.exists(unlist(paths))))
  manifest <- jsonlite::read_json(paths$integrity, simplifyVector = TRUE)
  expect_identical(manifest$package$version, "2.0.0")
  expect_gte(manifest$file_count, 9L)
})

test_that("connected API v2 retains review boundaries", {
  platform <- connected_sustainability_platform("platform-api", "API Platform", "institution-1", "Institution One")
  request <- connected_api_request("platform.summary")
  response <- dispatch_connected_api_request(request, platform)
  expect_identical(response$status, "ok")
  expect_false(response$boundary$automated_decision_authorization)
  manifest <- catalyst_connected_api_manifest()
  expect_identical(manifest$api_version, "v2")
  expect_identical(manifest$compatibility$public_api_v1$api_version, "v1")
})
