test_that("project publication exports portable analytical artifacts", {
  project <- project_fixture()
  dir <- tempfile("project-publication-")
  paths <- export_project_publication(project, dir, prefix = "publication", zip_bundle = TRUE)
  expect_true(file.exists(paths$project))
  expect_true(file.exists(paths$manifest))
  expect_true(file.exists(paths$run_index))
  expect_true(file.exists(paths$scenario_index))
  expect_true(file.exists(paths$dataset_index))
  expect_true(file.exists(paths$markdown))
  expect_true(file.exists(paths$html))
  expect_true(file.exists(paths$quarto))
  expect_true(file.exists(paths$decision_studio))
  expect_true(file.exists(paths$knowledge_library))
  expect_true(file.exists(paths$zip))

  manifest <- jsonlite::read_json(paths$manifest, simplifyVector = TRUE)
  expect_identical(manifest$schema_version, "1.0.0")
  expect_identical(manifest$package$version, "1.0.0")
  expect_identical(manifest$project_id, project$id)
  file_count <- if (is.data.frame(manifest$files)) nrow(manifest$files) else length(manifest$files)
  expect_gte(file_count, 8L)
  expect_identical(manifest$file_count, file_count)
  expect_identical(manifest$integrity$scope, "all_bundle_files_except_manifest")
})

test_that("platform handoffs preserve review and reproducibility boundaries", {
  project <- project_fixture()
  decision <- decision_studio_handoff(project)
  knowledge <- knowledge_library_handoff(project)
  expect_equal(decision$handoff_type, "decision_studio_analytical_project")
  expect_true(decision$decision_boundary$human_decision_required)
  expect_equal(length(decision$analytical_evidence), 1L)
  expect_equal(knowledge$handoff_type, "knowledge_library_methodology_package")
  expect_true(knowledge$publication_boundary$limitations_require_prominent_disclosure)
  expect_equal(knowledge$reproducibility$package_version, "1.0.0")
})

test_that("plot registration copies figures with integrity records", {
  project <- project_fixture()
  plot_path <- tempfile(fileext = ".png")
  grDevices::png(plot_path, width = 400, height = 300)
  graphics::plot(1:3, 1:3)
  grDevices::dev.off()
  project <- project_add_plot(project, "trajectory", plot_path, "Trajectory", "Illustrative figure", "baseline-run")
  dir <- tempfile("project-plot-export-")
  paths <- export_project_publication(project, dir, prefix = "publication", formats = c("json", "markdown"), zip_bundle = FALSE)
  manifest <- jsonlite::read_json(paths$manifest, simplifyVector = TRUE)
  expect_equal(if (is.data.frame(manifest$plots)) nrow(manifest$plots) else length(manifest$plots), 1L)
  plot_file <- if (is.data.frame(manifest$plots)) manifest$plots$file[[1L]] else manifest$plots[[1L]]$file
  expect_true(file.exists(file.path(paths$bundle_dir, plot_file)))
})
