test_that("inclusive development summary retains all major dimensions", {
  analysis <- example_inclusive_development()
  summary <- inclusive_development_summary(analysis)
  expect_s3_class(analysis, "catalyst_inclusive_development")
  expect_true(is.finite(summary$closing_inclusive_wealth))
  expect_true(is.finite(summary$adjusted_net_savings))
  expect_true(is.finite(summary$human_development_index))
  expect_true(is.finite(summary$gini))
  expect_true(is.finite(summary$composite_score))
})

test_that("inclusive development export writes provenance and trace files", {
  analysis <- example_inclusive_development()
  parent <- tempfile("inclusive-development-")
  paths <- export_inclusive_development(analysis, dir = parent, zip_bundle = FALSE)
  expect_true(file.exists(paths$analysis))
  expect_true(file.exists(paths$wealth))
  expect_true(file.exists(paths$adjusted_net_savings))
  expect_true(file.exists(paths$human_development))
  expect_true(file.exists(paths$distribution))
  expect_true(file.exists(paths$intergenerational))
  expect_true(file.exists(paths$composite))
  expect_true(file.exists(paths$brief))
  expect_true(file.exists(paths$manifest))
  payload <- jsonlite::fromJSON(paths$analysis, simplifyVector = FALSE)
  expect_identical(payload$analysis_type, "inclusive_wealth_human_development_distribution")
  expect_true(payload$review_boundary$composite_weights_require_review)
})
